cadence:
  environment:
    CASSANDRA_SEEDS: cassandra
    DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development_es.yaml
    ENABLE_ES: "true"
    ES_SEEDS: elasticsearch
    ES_VERSION: v7
    KAFKA_SEEDS: kafka
    PROMETHEUS_ENDPOINT_0: 0.0.0.0:8000
    PROMETHEUS_ENDPOINT_1: 0.0.0.0:8001
    PROMETHEUS_ENDPOINT_2: 0.0.0.0:8002
    PROMETHEUS_ENDPOINT_3: 0.0.0.0:8003
  repository:
    image: ubercadence/server
    tag: master-auto-setup
cadence-web:
  environment:
    CADENCE_TCHANNEL_PEERS: cadence:7933
  repository:
    image: ubercadence/web
    tag: latest
cassandra:
  repository:
    image: cassandra
    tag: "3.11"
elasticsearch:
  environment:
    discovery.type: single-node
  repository:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss
    tag: 7.9.3
grafana:
  repository:
    image: grafana/grafana
    tag: ""
kafka:
  environment:
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  repository:
    image: wurstmeister/kafka
    tag: 2.12-2.1.1
prometheus:
  repository:
    image: prom/prometheus
    tag: latest
zookeeper:
  repository:
    image: wurstmeister/zookeeper
    tag: 3.4.6
