apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-cadence'
  labels:
    katenary.io/component: cadence
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: cadence
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8001
      targetPort: 8001
    - protocol: TCP
      port: 8002
      targetPort: 8002
    - protocol: TCP
      port: 8003
      targetPort: 8003
    - protocol: TCP
      port: 7933
      targetPort: 7933
    - protocol: TCP
      port: 7934
      targetPort: 7934
    - protocol: TCP
      port: 7935
      targetPort: 7935
    - protocol: TCP
      port: 7939
      targetPort: 7939
    - protocol: TCP
      port: 7833
      targetPort: 7833
