apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-cadence-web'
  labels:
    katenary.io/component: cadence-web
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: cadence-web
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: cadence-web
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-cadence
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking cadence port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-cadence 8000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: cadence-web
          image: '{{ .Values.cadence-web.repository.image }}{{ if ne .Values.cadence-web.repository.tag "" }}:{{ .Values.cadence-web.repository.tag }}{{ end }}'
          ports:
            - name: cadence-web
              containerPort: 8088
          env:
            - name: CADENCE_TCHANNEL_PEERS
              value: '{{ tpl .Values.cadence-web.environment.CADENCE_TCHANNEL_PEERS . }}'

