apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-cassandra'
  labels:
    katenary.io/component: cassandra
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: cassandra
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: cassandra
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: cassandra
          image: '{{ .Values.cassandra.repository.image }}{{ if ne .Values.cassandra.repository.tag "" }}:{{ .Values.cassandra.repository.tag }}{{ end }}'
          ports:
            - name: cassandra
              containerPort: 9042

