apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-grafana'
  labels:
    katenary.io/component: grafana
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: grafana
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: grafana
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-prometheus
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking prometheus port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-prometheus 9090 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: grafana
          image: '{{ .Values.grafana.repository.image }}{{ if ne .Values.grafana.repository.tag "" }}:{{ .Values.grafana.repository.tag }}{{ end }}'
          ports:
            - name: grafana
              containerPort: 3000

