apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-prometheus'
  labels:
    katenary.io/component: prometheus
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: prometheus
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: prometheus
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: prometheus
          image: '{{ .Values.prometheus.repository.image }}{{ if ne .Values.prometheus.repository.tag "" }}:{{ .Values.prometheus.repository.tag }}{{ end }}'
          ports:
            - name: prometheus
              containerPort: 9090
          command:
            - --config.file=/etc/prometheus/prometheus.yml

